volumes:
  proddb-data:
    driver: local

services:
  proddb:
    image: postgres
    volumes:
      - proddb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: production
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
